import React, { useState, useEffect } from 'react';
import Parse from 'parse';
import './App.css';

function App() {
  const [noticias, setNoticias] = useState([]);
    const [cargando, setCargando] = useState(true);

      useEffect(() => {
          const cargarNoticias = async () => {
                // 1. Definir la consulta a la clase 'Noticia' en Back4app
                      const Noticia = Parse.Object.extend('Noticia');
                            const query = new Parse.Query(Noticia);
                                  
                                        // 2. Ejecutar la consulta
                                              try {
                                                      const results = await query.find();
                                                              
                                                                      // 3. Transformar los resultados de Parse a objetos simples
                                                                              const noticiasData = results.map(obj => ({
                                                                                        id: obj.id,
                                                                                                  titulo: obj.get('titulo'),
                                                                                                            resumen: obj.get('resumen'),
                                                                                                                      activos: obj.get('activos') || [] // Asegura que sea un array
                                                                                                                              }));
                                                                                                                                      
                                                                                                                                              setNoticias(noticiasData);
                                                                                                                                                      setCargando(false);
                                                                                                                                                            } catch (error) {
                                                                                                                                                                    console.error('Error al cargar noticias:', error);
                                                                                                                                                                            setCargando(false);
                                                                                                                                                                                  }
                                                                                                                                                                                      };

                                                                                                                                                                                          cargarNoticias();
                                                                                                                                                                                            }, []);

                                                                                                                                                                                              if (cargando) {
                                                                                                                                                                                                  return <div className="cargando">Cargando noticias que mueven el mercado...</div>;
                                                                                                                                                                                                    }

                                                                                                                                                                                                      return (
                                                                                                                                                                                                          <div className="app">
                                                                                                                                                                                                                <header>
                                                                                                                                                                                                                        <h1>📈 Market Mover News</h1>
                                                                                                                                                                                                                                <p>Impacto bursátil de las últimas noticias</p>
                                                                                                                                                                                                                                      </header>

                                                                                                                                                                                                                                            <main>
                                                                                                                                                                                                                                                    {noticias.length === 0 && <p>No hay noticias aún. ¡Crea la primera en Back4app!</p>}
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                    {noticias.map(noticia => (
                                                                                                                                                                                                                                                                              <article key={noticia.id} className="noticia">
                                                                                                                                                                                                                                                                                          <h2>{noticia.titulo}</h2>
                                                                                                                                                                                                                                                                                                      <p className="resumen">{noticia.resumen}</p>

                                                                                                                                                                                                                                                                                                                  <div className="activos">
                                                                                                                                                                                                                                                                                                                                <h3>Activos afectados:</h3>
                                                                                                                                                                                                                                                                                                                                              <div className="lista-activos">
                                                                                                                                                                                                                                                                                                                                                              {noticia.activos && noticia.activos.map((activo, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                <div key={idx} className={`activo ${activo.direccion}`}>
                                                                                                                                                                                                                                                                                                                                                                                                    <span className="ticker">{activo.ticker}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="nombre">{activo.nombre}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="direccion">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {activo.direccion === 'alta' ? '🔼' : activo.direccion === 'baja' ? '🔽' : '⚪'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="justificacion">{activo.justificacion}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Información con fines educativos. No es asesoramiento financiero.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default App;